
 DROP FUNCTION IF EXISTS public.bmi(integer, date) CASCADE;
 DROP FUNCTION IF EXISTS public.bmi_description(numeric) CASCADE;
 DROP FUNCTION IF EXISTS public.find_section(integer, date, integer) CASCADE;
 DROP FUNCTION IF EXISTS public.get_age(integer, timestamp without time zone) CASCADE;
 DROP FUNCTION IF EXISTS public.get_age(integer, date) CASCADE;
 DROP FUNCTION IF EXISTS public.get_best_stuff(integer) CASCADE;
 DROP FUNCTION IF EXISTS public.get_heigth(integer, date) CASCADE;
 DROP FUNCTION IF EXISTS public.get_my_med(integer, date) CASCADE;
 DROP FUNCTION IF EXISTS public.get_table(text) CASCADE;
 DROP FUNCTION IF EXISTS public.get_weight(integer, timestamp without time zone) CASCADE;
 DROP FUNCTION IF EXISTS public.heartrate_session_type(integer, integer) CASCADE;
 DROP FUNCTION IF EXISTS public.heartrates_check() CASCADE;
 DROP FUNCTION IF EXISTS public.height_weight_changes() CASCADE;
 DROP FUNCTION IF EXISTS public.height_weight_check() CASCADE;
 DROP FUNCTION IF EXISTS public.injuries_check() CASCADE;
 DROP FUNCTION IF EXISTS public.kcal(integer, timestamp without time zone, timestamp without time zone) CASCADE;
 DROP FUNCTION IF EXISTS public.kcal_during_session(integer, integer) CASCADE;
 DROP FUNCTION IF EXISTS public.max_heartrate(numeric) CASCADE;
 DROP FUNCTION IF EXISTS public.min_heartrate(numeric) CASCADE;
 DROP FUNCTION IF EXISTS public.section_ranking(integer, date, date) CASCADE;
 DROP FUNCTION IF EXISTS public.sections_check() CASCADE;
 DROP FUNCTION IF EXISTS public.sessions_check() CASCADE;
 DROP FUNCTION IF EXISTS public.sleep_check() CASCADE;
 DROP FUNCTION IF EXISTS public.time_interval_check(integer, timestamp without time zone, timestamp without time zone, text) CASCADE;
 DROP FUNCTION IF EXISTS public.timetable(integer, date, date) CASCADE ;
 DROP FUNCTION IF EXISTS public.user_section_check() CASCADE;
 DROP FUNCTION IF EXISTS public.user_session_check() CASCADE;                     

 DROP TABLE IF EXISTS "users" CASCADE;
 DROP TABLE IF EXISTS "sleep" CASCADE;
 DROP TABLE IF EXISTS "injuries" CASCADE;
 DROP TABLE IF EXISTS "height_weight" CASCADE;
 DROP TABLE IF EXISTS "heartrates" CASCADE;
 DROP TABLE IF EXISTS "medications" CASCADE;
 DROP TABLE IF EXISTS "activities" CASCADE;
 DROP TABLE IF EXISTS "user_section" CASCADE;
 DROP TABLE IF EXISTS "user_medication" CASCADE;
 DROP TABLE IF EXISTS "sections" CASCADE;
 DROP TABLE IF EXISTS "user_session" CASCADE;
 DROP TABLE IF EXISTS "sessions" CASCADE;

 DROP VIEW IF EXISTS user_min_max_heartrate CASCADE;
 DROP VIEW IF EXISTS activities_meds CASCADE;
 DROP VIEW IF EXISTS best_medication_sets CASCADE;
 DROP VIEW IF EXISTS actual_sections CASCADE;
 DROP VIEW IF EXISTS section_session CASCADE;
 DROP VIEW IF EXISTS individual_session CASCADE;

DROP RULE IF EXISTS actual_sections_INSERT ON actual_sections CASCADE;
DROP RULE IF EXISTS section_session_INSERT ON section_session CASCADE;
DROP RULE IF EXISTS section_session_DELETE ON section_session CASCADE;
DROP RULE IF EXISTS section_session_UPDATE ON section_session CASCADE;
DROP RULE IF EXISTS section_session_INSERT ON individual_session CASCADE;
DROP RULE IF EXISTS section_session_DELETE ON individual_session CASCADE;
DROP RULE IF EXISTS section_session_UPDATE ON individual_session CASCADE;
DROP RULE IF EXISTS trainer_session_INSERT ON sessions CASCADE;
DROP RULE IF EXISTS trainer_session_d_0 ON sessions CASCADE;
DROP RULE IF EXISTS trainer_session_d_3 ON sessions CASCADE;
DROP RULE IF EXISTS trainer_session_d_1 ON user_session CASCADE;
