 DROP FUNCTION sections_check() cascade;
 DROP FUNCTION sleep_check() cascade;
 DROP FUNCTION heartrates_check() cascade;
 DROP FUNCTION injuries_check() cascade;
 DROP FUNCTION sessions_check() cascade;
 DROP FUNCTION user_section_check() cascade ;
 DROP FUNCTION user_session_check() cascade;
 DROP FUNCTION heartrate_session_type(integer, integer) cascade;
 DROP FUNCTION section_timesheet(integer, date, date) cascade;
 DROP FUNCTION medications_sessions(integer, date, date) cascade;
 DROP FUNCTION choose_secion_for_user(integer) cascade ;
 DROP FUNCTION height_weight_changes(integer)cascade ;
 DROP FUNCTION get_table(text) cascade ;
 DROP FUNCTION time_interval_check(integer, timestamp without time zone, timestamp without time zone, text) cascade ;
 DROP FUNCTION kcal_during_session(integer, integer) cascade;
 drop table "medications" cascade;
 drop table "user_session" cascade;
 drop table "user_medication" cascade;
 drop table "user_section" cascade;
 drop table "sessions" cascade;
 drop table "heartrates" cascade;
 drop table "height_weight" cascade;
 drop table "accidents" cascade;
 drop table "injuries" cascade;
 drop table "users" cascade;
 drop table "sections" cascade;
 drop table "sleep" cascade;
 drop table "activities" cascade;

